Repository astrolabsoftware/fink-science, pull requests merged in 2021-06, with the labels that each got.

#107 Add 2PC model
  fink_science/data/models/KN_model_1PC.pkl
  fink_science/data/models/model_1PC_2KN_Cosmins_models.pkl
  fink_science/kilonova/lib_kn.py
  fink_science/kilonova/processor.py
Labels: kilonovae

#105 Image classification module
  fink_science/data/alerts/image_classification_example.parquet
  fink_science/image_classification/README.md
  fink_science/image_classification/image_classification.py
  fink_science/image_classification/pic/corrupted_clear.png
  fink_science/image_classification/pic/extend_object.png
  fink_science/image_classification/pic/safe_noisy.png
  fink_science/image_classification/pic/star_object.png
  fink_science/image_classification/processor.py
  fink_science/image_classification/utils.py
  requirements.txt
Labels: new module

#108 Bump to version 0.4.5
  fink_science/__init__.py
Labels: version

#111 add __init__.py file
  fink_science/image_classification/__init__.py
Labels: bug, image classification
