Repository astrolabsoftware/fink-science, pull requests merged in 2022-04, with the labels that each got.

#151 Use kndetect
  fink_science/kilonova/lib_kn.py
  fink_science/kilonova/processor.py
  fink_science/utilities.py
  requirements.txt
Labels: kilonovae

#143 Upgrade to Spark 3
  .github/workflows/linter.yml
  .github/workflows/run_test.yml
  fink_science/data/alerts/elasticc_parquet/_SUCCESS
  fink_science/data/alerts/elasticc_parquet/part-00000-9f78a16f-73f6-45b5-8ebb-567c3a1e6b01-c000.snappy.parquet
  fink_science/image_classification/image_classification.py
  fink_science/kilonova/processor.py
  fink_science/microlensing/processor.py
  fink_science/random_forest_snia/classifier_sigmoid.py
  fink_science/random_forest_snia/processor.py
  fink_science/random_forest_snia/sigmoid.py
  fink_science/snn/processor.py
  fink_science/snn/utilities.py
  fink_science/tester.py
  fink_science/utilities.py
  requirements.txt
  run_tests.sh
Labels: ci, spark 3

#160 Clean the repo from unused files
  .github/workflows/run_test.yml
  fink_science/asteroids/processor.py
  fink_science/conversion.py
  fink_science/kilonova/processor.py
  fink_science/microlensing/processor.py
  fink_science/nalerthist/processor.py
  fink_science/random_forest_snia/processor.py
  fink_science/snad/processor.py
  fink_science/snn/processor.py
  fink_science/utilities.py
Labels: cleaning

#161 Bump to 1.1.0
  fink_science/__init__.py
Labels: version

#165 Fix typo and update test suite...
  fink_science/__init__.py
  fink_science/kilonova/processor.py
Labels: bug, kilonovae
