Repository astrolabsoftware/fink-science, pull requests merged in 2022-10, with the labels that each got.

#238 [AGN] Replace nan/inf by 0.0 before inference
  fink_science/__init__.py
  fink_science/agn_elasticc/feature_extraction.py
Labels: bug, elasticc, AGN

#241 [Bug] Filter empty candidates in AGN Elasticc
  fink_science/agn_elasticc/classifier.py
Labels: elasticc, AGN

#246 [245] Fix failing test
  fink_science/cats/processor.py
Labels: test, elasticc

#247 Update to flux cal
  fink_science/snn/processor.py
Labels: bug, supernnova

#250 Add two new cases for AGN xmatch
  fink_science/data/catalogs/3hsp.csv
  fink_science/data/catalogs/table-4LAC-DR3-h.fits
  fink_science/data/catalogs/table-4LAC-DR3-l.fits
  fink_science/xmatch/processor.py
  fink_science/xmatch/utils.py
Labels: AGN
