Repository astrolabsoftware/fink-science, pull requests merged in 2024-07, with the labels that each got.

#400 Update the docker image for the test suite
  .github/workflows/run_test.yml
Labels: ci

#398 Add profiling capabilities
  .github/workflows/run_test.yml
  fink_science/ad_features/processor.py
  fink_science/agn/classifier.py
  fink_science/agn/feature_extraction.py
  fink_science/agn/models.py
  fink_science/agn/processor.py
  fink_science/anomaly_detection/processor.py
  fink_science/asteroids/processor.py
  fink_science/cats/processor.py
  fink_science/fast_transient_rate/processor.py
  fink_science/kilonova/processor.py
  fink_science/microlensing/processor.py
  fink_science/random_forest_snia/processor.py
  fink_science/slsn/classifier.py
  fink_science/slsn/feature_extraction.py
  fink_science/slsn/processor.py
  fink_science/snn/processor.py
  fink_science/t2/processor.py
  fink_science/xmatch/processor.py
  fink_science/xmatch/utils.py
Labels: performances

#396 Add hostless detection science module
  fink_science/data/alerts/hostless_detection/part-0-0-435829.parquet
  fink_science/hostless_detection/__init__.py
  fink_science/hostless_detection/config.json
  fink_science/hostless_detection/pipeline_utils.py
  fink_science/hostless_detection/powerspectrum.py
  fink_science/hostless_detection/processor.py
  fink_science/hostless_detection/run_pipeline.py
  run_tests.sh
  setup.py
Labels: new module

#405 Hostless: some cleaning
  fink_science/hostless_detection/config.json
  fink_science/hostless_detection/powerspectrum.py
  fink_science/hostless_detection/processor.py
  fink_science/hostless_detection/run_pipeline.py
Labels: performances, cleaning, hostless
